DISPLAY_WIDTH = 1280
DISPLAY_HEIGHT = 720

DISPLAY_SIZE = (DISPLAY_WIDTH, DISPLAY_HEIGHT)
DISPLAY_WIDTH_CENTER = DISPLAY_WIDTH // 2
DISPLAY_HEIGHT_CENTER = DISPLAY_HEIGHT // 2
DISPLAY_CENTER = (DISPLAY_WIDTH_CENTER, DISPLAY_HEIGHT_CENTER)

DEBUG_MODE = True

WINDOW_TITLE = "Pygame-CE Engine"
ROOT_ASSET_PATH = "assets"